// 日本語都市名を英語に変換するマッピング
export const cityMapping: Record<string, string> = {
  // 日本の主要都市
  '東京': 'Tokyo',
  '大阪': 'Osaka',
  '京都': 'Kyoto',
  '名古屋': 'Nagoya',
  '横浜': 'Yokohama',
  '神戸': 'Kobe',
  '福岡': 'Fukuoka',
  '札幌': 'Sapporo',
  '広島': 'Hiroshima',
  '仙台': 'Sendai',
  '千葉': 'Chiba',
  '北九州': 'Kitakyushu',
  '浜松': 'Hamamatsu',
  '熊本': 'Kumamoto',
  '相模原': 'Sagamihara',
  '岡山': 'Okayama',
  '鹿児島': 'Kagoshima',
  '金沢': 'Kanazawa',
  '高松': 'Takamatsu',
  '富山': 'Toyama',
  '奈良': 'Nara',
  '長崎': 'Nagasaki',
  '大分': 'Oita',
  '宮崎': 'Miyazaki',
  '沖縄': 'Okinawa',
  '那覇': 'Naha',
  '青森': 'Aomori',
  '盛岡': 'Morioka',
  '秋田': 'Akita',
  '山形': 'Yamagata',
  '福島': 'Fukushima',
  '水戸': 'Mito',
  '宇都宮': 'Utsunomiya',
  '前橋': 'Maebashi',
  'さいたま': 'Saitama',
  '甲府': 'Kofu',
  '長野': 'Nagano',
  '岐阜': 'Gifu',
  '静岡': 'Shizuoka',
  '津': 'Tsu',
  '和歌山': 'Wakayama',
  '鳥取': 'Tottori',
  '松江': 'Matsue',
  '徳島': 'Tokushima',
  '高知': 'Kochi',
  '佐賀': 'Saga',
  
  // 滋賀県の市町村（詳細対応）
  '滋賀': 'Shiga',
  '大津': 'Otsu',
  '大津市': 'Otsu',
  '彦根': 'Hikone',
  '彦根市': 'Hikone',
  '長浜': 'Nagahama',
  '長浜市': 'Nagahama',
  '近江八幡': 'Omihachiman',
  '近江八幡市': 'Omihachiman',
  '草津': 'Kusatsu',
  '草津市': 'Kusatsu',
  '守山': 'Moriyama',
  '守山市': 'Moriyama',
  '栗東': 'Ritto',
  '栗東市': 'Ritto',
  '甲賀': 'Koka',
  '甲賀市': 'Koka',
  '野洲': 'Yasu',
  '野洲市': 'Yasu',
  '湖南': 'Konan',
  '湖南市': 'Konan',
  '高島': 'Takashima',
  '高島市': 'Takashima',
  '東近江': 'Higashiomi',
  '東近江市': 'Higashiomi',
  '米原': 'Maibara',
  '米原市': 'Maibara',
  '日野': 'Hino Shiga',
  '日野町': 'Hino Shiga',
  '竜王': 'Ryuo',
  '竜王町': 'Ryuo',
  '愛荘': 'Aisho',
  '愛荘町': 'Aisho',
  '豊郷': 'Toyosato',
  '豊郷町': 'Toyosato',
  '甲良': 'Kora',
  '甲良町': 'Kora',
  '多賀': 'Taga',
  '多賀町': 'Taga',
  
  // 愛知県の市町村（詳細対応）
  '愛知': 'Aichi',
  '豊橋': 'Toyohashi',
  '豊橋市': 'Toyohashi',
  '岡崎': 'Okazaki',
  '岡崎市': 'Okazaki',
  '一宮': 'Ichinomiya',
  '一宮市': 'Ichinomiya',
  '瀬戸': 'Seto',
  '瀬戸市': 'Seto',
  '半田': 'Handa',
  '半田市': 'Handa',
  '春日井': 'Kasugai',
  '春日井市': 'Kasugai',
  '豊川': 'Toyokawa',
  '豊川市': 'Toyokawa',
  '津島': 'Tsushima',
  '津島市': 'Tsushima',
  '碧南': 'Hekinan',
  '碧南市': 'Hekinan',
  '刈谷': 'Kariya',
  '刈谷市': 'Kariya',
  '豊田': 'Toyota',
  '豊田市': 'Toyota',
  '安城': 'Anjo',
  '安城市': 'Anjo',
  '西尾': 'Nishio',
  '西尾市': 'Nishio',
  '蒲郡': 'Gamagori',
  '蒲郡市': 'Gamagori',
  '犬山': 'Inuyama',
  '犬山市': 'Inuyama',
  '常滑': 'Tokoname',
  '常滑市': 'Tokoname',
  '江南': 'Konan Aichi',
  '江南市': 'Konan Aichi',
  '小牧': 'Komaki',
  '小牧市': 'Komaki',
  '稲沢': 'Inazawa',
  '稲沢市': 'Inazawa',
  '新城': 'Shinshiro',
  '新城市': 'Shinshiro',
  '東海': 'Tokai',
  '東海市': 'Tokai',
  '大府': 'Obu',
  '大府市': 'Obu',
  '知多': 'Chita',
  '知多市': 'Chita',
  '知立': 'Chiryu',
  '知立市': 'Chiryu',
  '尾張旭': 'Owariasahi',
  '尾張旭市': 'Owariasahi',
  '高浜': 'Takahama',
  '高浜市': 'Takahama',
  '岩倉': 'Iwakura',
  '岩倉市': 'Iwakura',
  '豊明': 'Toyoake',
  '豊明市': 'Toyoake',
  '日進': 'Nisshin',
  '日進市': 'Nisshin',
  '田原': 'Tahara',
  '田原市': 'Tahara',
  '愛西': 'Aisai',
  '愛西市': 'Aisai',
  '清須': 'Kiyosu',
  '清須市': 'Kiyosu',
  '北名古屋': 'Kitanagoya',
  '北名古屋市': 'Kitanagoya',
  '弥富': 'Yatomi',
  '弥富市': 'Yatomi',
  'みよし': 'Miyoshi',
  'みよし市': 'Miyoshi',
  'あま': 'Ama',
  'あま市': 'Ama',
  '長久手': 'Nagakute',
  '長久手市': 'Nagakute',
  '東郷': 'Togo',
  '東郷町': 'Togo',
  '豊山': 'Toyoyama',
  '豊山町': 'Toyoyama',
  '大口': 'Oguchi',
  '大口町': 'Oguchi',
  '扶桑': 'Fuso',
  '扶桑町': 'Fuso',
  '大治': 'Oharu',
  '大治町': 'Oharu',
  '蟹江': 'Kanie',
  '蟹江町': 'Kanie',
  '飛島': 'Tobishima',
  '飛島村': 'Tobishima',
  '阿久比': 'Agui',
  '阿久比町': 'Agui',
  '東浦': 'Higashiura',
  '東浦町': 'Higashiura',
  '南知多': 'Minamichita',
  '南知多町': 'Minamichita',
  '美浜': 'Mihama',
  '美浜町': 'Mihama',
  '武豊': 'Taketoyo',
  '武豊町': 'Taketoyo',
  '幸田': 'Kota',
  '幸田町': 'Kota',
  '設楽': 'Shitara',
  '設楽町': 'Shitara',
  '東栄': 'Toei',
  '東栄町': 'Toei',
  '豊根': 'Toyone',
  '豊根村': 'Toyone',
  
  // 世界の主要都市（日本語表記）
  'ロンドン': 'London',
  'パリ': 'Paris',
  'ニューヨーク': 'New York',
  'ロサンゼルス': 'Los Angeles',
  'シカゴ': 'Chicago',
  'ベルリン': 'Berlin',
  'ローマ': 'Rome',
  'マドリード': 'Madrid',
  'アムステルダム': 'Amsterdam',
  'ウィーン': 'Vienna',
  'ブリュッセル': 'Brussels',
  'ストックホルム': 'Stockholm',
  'オスロ': 'Oslo',
  'コペンハーゲン': 'Copenhagen',
  'ヘルシンキ': 'Helsinki',
  'モスクワ': 'Moscow',
  'シドニー': 'Sydney',
  'メルボルン': 'Melbourne',
  'シンガポール': 'Singapore',
  'バンコク': 'Bangkok',
  'クアラルンプール': 'Kuala Lumpur',
  'ジャカルタ': 'Jakarta',
  'マニラ': 'Manila',
  'ソウル': 'Seoul',
  '釜山': 'Busan',
  '北京': 'Beijing',
  '上海': 'Shanghai',
  '香港': 'Hong Kong',
  '台北': 'Taipei',
  'ムンバイ': 'Mumbai',
  'デリー': 'Delhi',
  'バンガロール': 'Bangalore',
  'ドバイ': 'Dubai',
  'イスタンブール': 'Istanbul',
  'カイロ': 'Cairo',
  'ケープタウン': 'Cape Town',
  'リオデジャネイロ': 'Rio de Janeiro',
  'サンパウロ': 'Sao Paulo',
  'ブエノスアイレス': 'Buenos Aires',
  'メキシコシティ': 'Mexico City',
  'トロント': 'Toronto',
  'バンクーバー': 'Vancouver',
};

// 日本語の都市名を英語に変換する関数
export const convertJapaneseCityToEnglish = (cityName: string): string => {
  const trimmedCity = cityName.trim();
  
  // 完全一致での検索
  if (cityMapping[trimmedCity]) {
    return cityMapping[trimmedCity];
  }
  
  // 部分一致での検索（都、府、県、市を除いた名前で検索）
  const cityWithoutSuffix = trimmedCity.replace(/[都府県市]$/, '');
  if (cityMapping[cityWithoutSuffix]) {
    return cityMapping[cityWithoutSuffix];
  }
  
  // マッピングに無い場合はそのまま返す（英語名の可能性）
  return trimmedCity;
}; 